<?php

/**
 * Metadata version
 */

use OxidEsales\Eshop\Application\Controller\OrderController;
use OxidEsales\Eshop\Application\Model\Order;
use OxidEsales\Eshop\Application\Model\BasketItem;
use OxidEsales\Eshop\Application\Model\PaymentGateway;

$sMetadataVersion = '2.0';
/**
 * Module information
 */
$aModule = array(
    'id' => 'eimed_commdoo_payment',
    'title' => array(
        'de' => 'CommDoo Payment by EIKONA Media',
        'en' => 'CommDoo Payment by EIKONA Media',
    ),
    'description' => array(
        'de' => '<h2>OXID6 Payment Modul</h2>',
        'en' => '<h2>OXID6 payment module</h2>',
    ),
    'thumbnail' => 'out/pictures/commdoo_payment_logo.png',
    'version' => '1.0.2',
    'author' => 'EIKONA Media GmbH',
    'url' => 'https://www.eikona-media.de',
    'email' => 'info@eikona-media.de',
    'extend' => array(
        OrderController::class => \Eimed\Modules\CommdooPayment\Controller\OrderController::class,
        Order::class           => \Eimed\Modules\CommdooPayment\Model\CommDooOrder::class,
        PaymentGateway::class  => \Eimed\Modules\CommdooPayment\Model\CommDooPaymentGateway::class,
        BasketItem::class      => \Eimed\Modules\CommdooPayment\Model\CommDooBasketItem::class,
    ),
    'events' => array(
        'onActivate'   => 'Eimed\Modules\CommdooPayment\Module::onActivate',
        'onDeactivate' => 'Eimed\Modules\CommdooPayment\Module::onDeactivate',
    ),
    'settings' => [
        [
            'group' => 'api',
            'name' => 'sCD_clientid',
            'type' => 'str',
            'value' => '99999999'
        ],
        [
            'group' => 'api',
            'name' => 'sCD_sharedsecret',
            'type' => 'str',
            'value' => 'test',
        ],
        [
            "group" => "api",
            "name" => "sCD_baseurl",
            'type' => 'str',
            'value' => 'https://frontend.payment-transaction.net/payment.aspx?',
        ],
        [
            "group" => "api",
            "name" => "sCD_successurl",
            "type" => "str",
            "value" => "CommDooPaymentSuccessful/",
        ],
        [
            "group" => "api",
            "name" => "sCD_failurl",
            "type" => "str",
            "value" => "CommDooPaymentFailed/",
        ],
        [
            "group" => "transaction",
            "name" => "sCD_paymentmode",
            "type" => 'select',
            'constraints' => '0|reservation',
            'value' => 'reservation'
        ],
        [
            "group" => "transaction",
            "name" => "sCD_cancelMode",
            "type" => 'select',
            'constraints' => 'delete|cancel',
            'value' => 'cancel'
        ],
        [
            "group" => "internal",
            "name" => "aCD_frontend_request_params",
            "type" => "arr",
            "value" => array(
                "clientid",
                "payment",
                "avskey",
                "paymentmode",
                "referenceid",
                "orderid",
                "customerid",
                "referencecustomerid",
                "language",
                // "“partially”",   // not supported
                // "“makepayment”", // not supported
                "amount",
                "currency",
                "collectionreference",
                "companyname",
                "title",
                "salutation",
                "firstname",
                "lastname",
                "dateofbirth",
                "idcardnumber",
                "street",
                "housenumber",
                "postalcode",
                "city",
                "state",
                "country",
                "phonenumber",
                "emailaddress",
                "deviceid1",
                "deviceid2",
                "ipaddress",
                "bankaccountholder",
                "bankcountry",
                "iban",
                "bic",
                "creditcardnumber",
                "expirationmonth",
                "expirationyear",
                "creditcardtype",
                "cvv",
                "creditcardowner",
                "timeunit",
                "billingcycle",
                "durationperiod",
                "renewalperiod",
                "minimumdurationperiod",
                "maximumdurationperiod",
                "cancellationperiod",
                "trialdurationperiod",
                "trialtimeunit",
                "trialamount",
                "successurl",
                "failurl",
                "backurl",
                "notificationurl",
                "additionaldata",
                "timestamp",
                "delivery-companyname",
                "delivery-salutation",
                "delivery-title",
                "delivery-firstname",
                "delivery-lastname",
                "delivery-street",
                "delivery-housenumber",
                "delivery-postalcode",
                "delivery-city",
                "delivery-state",
                "delivery-country",
                "delivery-phonenumber",
                "delivery-emailaddress",
                "item[x]-id",
                "item[x]-name",
                "item[x]-description",
                "item[x]-quantity",
                "item[x]-totalprice",
                "item[x]-currency",
                "item[x]-taxpercentage",
                "website",
                "layout",
                "relatedinformation-username",
                "relatedinformation-tariff",
                "relatedinformation-tarifftitle",
                "relatedinformation-dateofregistration",
                "relatedinformation-amazonorderreferenceid",
                "relatedinformation-orderdescription",
                "relatedinformation-purpose",
                "relatedinformation-endpointid",
                "relatedinformation-endpointgroupid",
                "relatedinformation-account-accountageindicator",
                "relatedinformation-account-accountlastchangedate",
                "relatedinformation-account-accountlastchangeindicator",
                "relatedinformation-account-accountcreationdate",
                "relatedinformation-account-passwordchangedate",
                "relatedinformation-account-passwordchangeindicator",
                "relatedinformation-account-purchaseslast6months",
                "relatedinformation-account-paymentaccountcreationdate",
                "relatedinformation-account-paymentaccountcreationindicator",
                "relatedinformation-account-addpaymentaccountattemptslast24hours",
                "relatedinformation-account-shippingaddressfirstusagedate",
                "relatedinformation-account-shippingaddressfirstusageindicator",
                "relatedinformation-account-shippingnameindicator",
                "relatedinformation-account-suspiciousactivityindicator",
                "relatedinformation-account-numberofpaymentrequestslast24hours",
                "relatedinformation-account-numberofpaymentrequestslast12months",
                "relatedinformation-account-homephonenumber",
                "relatedinformation-account-mobilephonenumber",
                "relatedinformation-account-workphonenumber",
                "relatedinformation-account-shippingemailaddress",
                "relatedinformation-purchase-transactiontype",
                "relatedinformation-purchase-shippingmethodindicator",
                "relatedinformation-purchase-shippingtimeframe",
                "relatedinformation-purchase-preorderavailabilitydate",
                "relatedinformation-purchase-preorderavailabilityindicator",
                "relatedinformation-purchase-reorderitemsindicator",
                "relatedinformation-purchase-prepaidandgiftcardamount",
                "relatedinformation-purchase-prepaidandgiftcardcurrency",
                "relatedinformation-purchase-prepaidandgiftcardcount",
                "relatedinformation-browser-acceptheader",
                "relatedinformation-browser-useragentheader",
                "relatedinformation-browser-language",
                "relatedinformation-browser-timezoneoffset",
                "relatedinformation-browser-javaenabled",
                "relatedinformation-browser-javascriptenabled",
                "relatedinformation-browser-screenwidth",
                "relatedinformation-browser-screenheight",
                "relatedinformation-browser-colordepth",
                "relatedinformation-browser-challengewindowsize",
                "relatedinformation-authentication-authenticationdata",
                "relatedinformation-authentication-authenticationmethod",
                "relatedinformation-authentication-authenticationtimestamp",
                "relatedinformation-authentication-priorauthenticationdata",
                "relatedinformation-authentication-priorauthenticationmethod",
                "relatedinformation-authentication-priorauthenticationtimestamp",
                "relatedinformation-authentication-priorauthenticationreference",
            ),
        ],
        [
            "group" => "internal",
            "name" => "aCD_frontend_successful_response_params",
            "type" => "arr",
            "value" => array(
                "clientid",
                "transactionid",
                "referenceid",
                "subscriptionid",
                "amount",
                "currency",
                "paymentmethod",
                "customerid",
                "transactionstatus",
                "transactionstatusaddition",
                "creditcardtype",
                "providertransactionid",
                "providerpurpose",
                "additionaldata",
                "timestamp"
            ),
        ],
        [
            "group" => "internal",
            "name" => "aCD_frontend_failed_response_params",
            "type" => "arr",
            "value" => array(
                "clientid",
                "referenceid",
                "errornumber",
                "errortext",
                "additionaldata",
                "timestamp"
            ),
        ],
    ],
);
